import streamlit as st
import os
import sys
import datetime as dt

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from _shared import inject_base_css, PAGE_ICON
from reports.report_generator import generate_pdf_report, generate_excel_report

st.set_page_config(page_title="Reports", page_icon=PAGE_ICON, layout="wide")
inject_base_css(st)
st.title("📄 Reports")

st.write(
    "Generate a fresh report from the current data at any time. The PDF is a "
    "board/stakeholder-ready summary with KPIs, charts, and top performer tables. "
    "The Excel workbook contains a sheet per analytical view with native charts, "
    "for staff who want to dig into the numbers themselves."
)

out_dir = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "generated_reports"
)
os.makedirs(out_dir, exist_ok=True)
timestamp = dt.datetime.now().strftime("%Y%m%d_%H%M%S")

XLSX_MIME = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"


def render_report_card(column, key, title, caption, button_label, generate, filename, mime, spinner):
    """
    Generate-then-download card.

    The generated bytes are parked in st.session_state rather than rendered
    inside the `if st.button(...)` branch: any later interaction on the page
    (including clicking the download button itself, which triggers a rerun)
    makes that branch False, which would otherwise wipe out the download
    button before the user could use it.
    """
    with column:
        st.subheader(title)
        st.caption(caption)
        if st.button(button_label, type="primary"):
            with st.spinner(spinner):
                path = generate(os.path.join(out_dir, filename))
            with open(path, "rb") as f:
                st.session_state[key] = {"name": os.path.basename(path), "bytes": f.read()}
        ready = st.session_state.get(key)
        if ready:
            st.download_button(
                f"⬇️ Download {mime_label(mime)}", ready["bytes"],
                file_name=ready["name"], mime=mime,
            )
            st.success(f"{ready['name']} ready.")


def mime_label(mime):
    return "PDF" if mime == "application/pdf" else "Excel"


col1, col2 = st.columns(2)

render_report_card(
    col1, "pdf_report", "📑 PDF Board Report",
    "KPI summary, funding trend, industry mix, top performers, event ROI.",
    "Generate PDF Report", generate_pdf_report,
    f"incubator_report_{timestamp}.pdf", "application/pdf",
    "Building PDF report...",
)

render_report_card(
    col2, "excel_report", "📊 Excel Analytics Workbook",
    "One sheet per view: top startups, mentors, investors, funding trend, event ROI, and more.",
    "Generate Excel Workbook", generate_excel_report,
    f"incubator_workbook_{timestamp}.xlsx", XLSX_MIME,
    "Building Excel workbook...",
)

st.divider()
st.caption(
    "Reports are generated on demand from live data, so numbers always reflect "
    "whatever is currently in the database and NoSQL collections."
)
